version: '3.8'

volumes:
  db_data:

networks:
  api-platform:
    name: api-platform-network

services:

  nginx:
    image: nginx:1.19.3-alpine
    container_name: nginx
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - api-platform

  php:
    image: vagifrzada/phpdock:latest
    container_name: php
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - api-platform

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: api_platform
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: api_platform
      SERVICE_NAME: mysql
      TZ: Asia/Baku
    command: --sql_mode=""
    networks:
      - api-platform

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - api-platform